# Generated by Django 3.2.9 on 2022-08-23 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('mat', models.TextField(unique=True)),
                ('nc', models.TextField(primary_key=True, serialize=False)),
                ('vbrand', models.TextField()),
                ('vmodel', models.TextField()),
                ('short_description', models.TextField()),
            ],
        ),
    ]
