# Generated by Django 3.2.9 on 2022-08-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicules_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicule',
            name='current_location',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='isStolen',
            field=models.BooleanField(default=False),
        ),
    ]
